export const oneByteList = {
    0x00: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x01: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x02: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x03: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x04: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x05: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x06: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x07: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x10: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x11: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x12: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x13: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x14: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x15: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x16: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x17: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x20: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x21: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x22: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x23: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x24: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x25: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x27: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x30: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x31: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x32: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x33: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x34: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x35: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x37: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x40: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x41: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x42: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x43: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x44: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x45: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x46: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x47: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x50: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x51: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x52: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x53: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x54: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x55: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x56: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x57: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x60: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x61: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x62: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x63: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x70: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x71: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x72: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x73: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x74: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x75: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x76: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x77: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x80: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x81: { opSize: 0, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x82: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x83: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x84: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x85: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x86: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x87: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x88: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x89: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8A: { opSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8B: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8C: { opSize: 2, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8D: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8E: { opSize: 2, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x8F: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x90: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x91: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x92: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x93: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x94: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x95: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x96: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x97: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA0: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA1: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA2: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA3: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA4: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA5: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA6: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA7: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB0: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB1: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB2: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB3: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB4: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB5: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB6: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB7: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB8: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB9: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBA: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBB: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBC: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBD: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBE: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBF: { opSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC0: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC1: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC2: { opSize: 2, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC3: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC4: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC5: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC6: { opSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC7: { opSize: 0, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD0: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD1: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD2: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD3: { opSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE0: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE1: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE2: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE3: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE4: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE5: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE6: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE7: { opSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF1: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF4: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF5: { opSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
};

/**
 * Possíveis problemas:
 *   F6, F7   - Pode ter ou não imm dependendo do campo REG no ModR/M
 */

/**
 * opSize:
 *   The size in bytes of the operand value.
 *   0 if is defined by operand-size.
 *
 * hasImm:
 *   Defines if the instruction has an immediate operand.
 *
 * hasModRM:
 *   Defines if the instruction has a ModR/M byte.
 *
 * only64bit:
 *   Defines if the instruction is only valid in 64-bit mode.
 *
 * invalid64bit:
 *   Defines if the instruction is invalid in 64-bit mode.
 *
 * hasAddressSizeOffset:
 *   Defines if the instruction has a displacement with size defined by address-size.
 */
