export const oneByteList = {
    0x00: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x01: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x02: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x03: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x04: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x05: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x06: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x07: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x10: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x11: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x12: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x13: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x14: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x15: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x16: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x17: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x20: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x21: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x22: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x23: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x24: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x25: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x27: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x30: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x31: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x32: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x33: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x34: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x35: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x37: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x40: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x41: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x42: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x43: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x44: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x45: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x46: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x47: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x50: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x51: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x52: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x53: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x54: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x55: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x56: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x57: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x60: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x61: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x62: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x63: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x70: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x71: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x72: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x73: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x74: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x75: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x76: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x77: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x80: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x81: { immSize: 0, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x82: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: true, hasAddressSizeOffset: false },
    0x83: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x84: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x85: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x86: { immSize: 1, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x87: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x90: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x91: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x92: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x93: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x94: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x95: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x96: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0x97: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA0: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA1: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA2: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA3: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: true },
    0xA4: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA5: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA6: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xA7: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB0: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB1: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB2: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB3: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB4: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB5: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB6: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB7: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB8: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xB9: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBA: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBB: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBC: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBD: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBE: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xBF: { immSize: 0, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC0: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC1: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC2: { immSize: 2, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC3: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC4: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC5: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC6: { immSize: 1, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xC7: { immSize: 0, hasImm: true, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD0: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD1: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD2: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xD3: { immSize: 0, hasImm: false, hasModRM: true, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE0: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE1: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE2: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE3: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE4: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE5: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE6: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xE7: { immSize: 1, hasImm: true, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF1: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF4: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
    0xF5: { immSize: 0, hasImm: false, hasModRM: false, only64bit: false, invalid64bit: false, hasAddressSizeOffset: false },
};

/**
 * Possíveis problemas:
 *   F6, F7   - Pode ter ou não imm dependendo do campo REG no ModR/M
 */

/**
 * immSize:
 *   The size in bytes of the immediate value.
 *   0 if is defined by operand-size.
 *
 * hasImm:
 *   Defines if the instruction has an immediate operand.
 *
 * hasModRM:
 *   Defines if the instruction has a ModR/M byte.
 *
 * only64bit:
 *   Defines if the instruction is only valid in 64-bit mode.
 *
 * invalid64bit:
 *   Defines if the instruction is invalid in 64-bit mode.
 *
 * hasAddressSizeOffset:
 *   Defines if the instruction has a displacement with size defined by address-size.
 */
